replicaCount: 3

image:
  repository: ghcr.io/girmaat/demo-api
  tag: prod-v1.2.3
  pullPolicy: IfNotPresent

service:
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 6
  periodSeconds: 10

strategy:
  type: canary
  canary:
    steps:
      - setWeight: 10
      - pause: {}
      - analysis:
          templateName: demo-api-success-rate
          args:
            - name: service-name
              value: demo-api
      - setWeight: 50
      - pause: {}
      - setWeight: 100
