replicaCount: 3

image:
  repository: ghcr.io/girmaat/frontend
  tag: prod-v1.0.0
  pullPolicy: IfNotPresent

service:
  port: 3000

resources:
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 6
  periodSeconds: 10

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 65

strategy:
  strategy:
    type: blueGreen