replicaCount: 1

image:
  repository: ghcr.io/girmaat/frontend
  tag: dev-latest
  pullPolicy: IfNotPresent

service:
  port: 3000

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20

hpa:
  enabled: false

strategy:
  type: canary
  canary:
    steps:
      - setWeight: 20
      - pause: { duration: 30s }
      - setWeight: 100
