# Sample values for demo-api
# These are not used in production — real values live in overlays/<env>/values/demo-api-values.yaml

replicaCount: 2

image:
  repository: ghcr.io/example/demo-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

strategy:
  type: canary
  canary:
    steps:
      - setWeight: 50
      - pause: { duration: 30s }

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
